---
title: "Plots to publish"
output:
  pdf_document: 
    fig_height: 8
    fig_width: 14
  html_notebook: default
  word_document: 
    fig_height: 8
    fig_width: 14
  html_document: 
    fig_height: 8
    fig_width: 14
---


```{r}
library(ggplot2)
library(ggpubr)
library(CDM)
library(boot)
library(tidyverse)
library(stringi)
library(stringr)
library(ggridges)
library(ggrepel)
```

```{r}
rm(list = ls())
options(max.print=100)
path = "report"
#path = ""


```


```{r}
df.error.ec <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_ecpe.rds"))

df.error.ec.agg <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_agg_ecpe.rds"))

df.error.ec.fit <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_fit_ecpe.rds")) %>% mutate(dataset = "ECPE")

df.error.ec.plot <- df.error.ec %>% inner_join(
  df.error.ec.agg
) %>% mutate(dataset = "ECPE")

df.error.ec.plot


```


```{r}
df.error.ti <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_timss.rds"))

df.error.ti.agg <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_agg_timss.rds"))

df.error.ti.fit <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_fit_timss.rds")) %>% mutate(dataset = "TIMSS")

df.error.ti.plot <- df.error.ti %>% inner_join(
  df.error.ti.agg
) %>% mutate(dataset = "TIMSS")


```


```{r}
df.error.ti.u <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_upsample_timss.rds"))

df.error.ti.agg.u <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_agg_upsample_timss.rds"))

df.error.ti.fit.u <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_fit_upsample_timss.rds")) %>% mutate(dataset = "TIMSS")

df.error.ti.plot.u <- df.error.ti.u %>% inner_join(
  df.error.ti.agg.u
) %>% mutate(dataset = "TIMSS")


```

```{r}
df.error.ss <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_socialscience.rds"))

df.error.ss.agg <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_agg_socialscience.rds"))

df.error.ss.fit <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_fit_socialscience.rds")) %>% mutate(dataset = "Social Psychology")

df.error.ss.plot <- df.error.ss %>% inner_join(
  df.error.ss.agg
) %>% mutate(dataset = "Social Psychology (Original)")

df.error.ss.plot

```

```{r}
df.error.ss.u <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_upsample_socialscience.rds"))

df.error.ss.agg.u <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_agg_upsample_socialscience.rds"))

df.error.ss.fit.u <- read_rds(paste0("..\\data\\FirstYearProject\\",path,"\\df_error_fit_upsample_socialscience.rds")) %>% mutate(dataset = "Social Psychology (Upsample)")

df.error.ss.plot.u <- df.error.ss.u %>% inner_join(
  df.error.ss.agg.u
) %>% mutate(dataset = "Social Psychology")

df.error.ss.plot.u

```


```{r}

df.error.ss.plot.u %>% 
  ggplot() + 
  aes(x = attempts, y = sampling_error) + 
  facet_wrap(group~., scales = "free")+
  geom_col() + scale_y_continuous(limits = c(0,1))

df.error.ss.plot.u %>% group_by(group, round(attempts)) %>% summarise(n=n(), se1 = min(sampling_error), se2 = max(sampling_error))

```




# Merge all Data

```{r}

df.error.plot <- df.error.ec.plot %>% 
  
  #bind_rows(df.error.ti.plot) %>% bind_rows(df.error.ss.plot) %>% 
  bind_rows(df.error.ti.plot.u) %>% bind_rows(df.error.ss.plot.u) %>% 
  
  mutate(ratio_n = as.numeric(student_question_ratio)) %>%
  
  mutate(student_question_ratio = factor(student_question_ratio, levels = sort(unique(as.numeric(student_question_ratio))), ordered = TRUE)) %>%
  
  mutate(dataset = factor(dataset, levels = c("ECPE", "TIMSS", "Social Psychology"))) %>% #
  
  mutate(questions = factor(questions)) %>% 
  
  group_by(dataset, group, parameter, sample_size) %>%
  
  mutate(question_n = n(), qsr = round(n()/sample_size)) %>% 
  
  mutate(attempts = round(attempts)) %>% 
  
  #Average attempts between partitions for each question.
  group_by(dataset, parameter, questions, student_question_ratio) %>%
  mutate(attempts_disc_n = round(mean(attempts))) %>% ungroup() %>%
  mutate(attempts_disc = cut(attempts_disc_n, 
                        breaks = c(0,5,10,15,20,25,30,40,50,60, 100, 200, 400, 800, max(.$attempts)),
                        labels = c(5,10,15,20,25,30,40,50,60, 100, 200, 400, 800, "1000+"),
                        include.lowest = TRUE, right = TRUE, ordered_result = TRUE))  %>%
  
  # Adding upsample column to represent attempts that were generated due to non-parameteric bootstrap upsampling

  mutate(upsampled = case_when(
    (dataset == "TIMSS" & attempts > 200)  ~ "Upsampled Attempts", #ratio_n > 21
    (dataset == "Social Psychology" & attempts > 15)  ~ "Upsampled Attempts", #ratio_n > 0.5
    TRUE ~ "Original Items"
    
    
  )) %>%
  
  
  #mutate(sampling_error = sampling_error / sqrt(1000)) %>% # To get Smulation Error
  
  # Average avg_attempts between partitions aggregated over all questions.
  
  group_by(dataset, parameter, attempts) %>%
  mutate(avg_attempts = round(mean(avg_attempts))) %>%
  
  ungroup() %>%
  arrange(dataset, group, parameter, sample_size)

df.error.plot <- df.error.plot %>% mutate(qsr = factor(qsr, ordered = TRUE), 
                                          sample_size = factor(sample_size, ordered = TRUE), 
                                          avg_attempts = factor(avg_attempts, ordered = TRUE)
                                          )
distinct(df.error.plot, dataset, upsampled, student_question_ratio, attempts_disc_n) 

summary(df.error.plot$attempts)


```

```{r}

df.fit.plot <- df.error.ec.fit %>% bind_rows(df.error.ti.fit) %>% bind_rows(df.error.ss.fit) %>% bind_rows(df.error.ss.fit.u)
#df.fit.plot

```


# Sampling Error



```{r}

df.error.plot %>% select(parameter, group, questions, sampling_error, attempts_disc, student_question_ratio, dataset) %>% 
  spread(key="group", value = "sampling_error") %>% arrange(attempts_disc) %>% filter(parameter == "Guess") %>%
  
  
  
  ggplot() + 
  aes(x=`Partition 1`, y=`Partition 2`, color = parameter) +
  geom_point(show.legend = TRUE, alpha = 0.4) +
  facet_grid(dataset~attempts_disc, scales = "free") + 
  ggtitle("Distribution of Sampling Mean for each Sample Size") + 
  scale_x_continuous(breaks = c(0,0.5)) + 
  scale_y_continuous(breaks = c(0,0.5)) + 
  ggpubr::theme_pubclean() + 
  labs(color = "", subtitle = "Student Sample Size") + 
  theme(legend.position = "bottom")

```

```{r}

#df.t <- df.error.plot %>% group_by(parameter, dataset, group, attempts_disc) %>% summarise(outlier_count = length(boxplot.stats(sampling_error)$out), n = n())


df.error.plot %>% select(parameter, group, questions, sampling_error, attempts_disc, student_question_ratio, dataset) %>% 
  ggplot() + 
  aes(x=attempts_disc, y = sampling_error, color = group)+
  #geom_boxplot(alpha = 0.3, position = position_dodge()) + 
  geom_jitter(position = position_dodge(width = 0.5), alpha = 0.035, aes(color = group))+
  stat_summary(fun.y = mean, geom = "line", aes(group = 1, color = "Mean of Sampling Error"), size =1 ) + 
  facet_grid(parameter~dataset, scale = "free") +
  theme_pubclean() + 
  labs(fill = "", x = "Examinee Attempt Size (EAS) of Item", title = "Sampling Error for each partition", color = "") + 
  theme(legend.position = "bottom") + #+
  #geom_text(data = df.t, aes(x=attempts_disc, y = 1.2, label = paste0(round(outlier_count / n,2) * 100, "%"), color = group), position = position_dodge()) 
  guides(colour = guide_legend(override.aes = list(alpha = 1)))

```



```{r}

df.mean_diff <- df.error.plot  %>% select(parameter, group, questions, sampling_mean, student_question_ratio, attempts_disc, dataset, upsampled) %>% 
  spread(key="group", value = "sampling_mean") %>% rename("Partition1_mean" = `Partition 1`, "Partition2_mean" = `Partition 2`)  %>% 
  
  group_by(dataset,parameter,student_question_ratio,questions) %>% 
  mutate(mean_diff = Partition1_mean - Partition2_mean)  
  

df.error_diff <- df.error.plot  %>% select(parameter, group, questions, sampling_error, student_question_ratio, attempts_disc, dataset, upsampled) %>% 
  spread(key="group", value = "sampling_error") %>% rename("Partition1_error" = `Partition 1`, "Partition2_error" = `Partition 2`)  %>% 
  
  group_by(dataset,parameter,student_question_ratio,questions) %>% 
  mutate(error_diff = Partition1_error - Partition2_error)  

  
```



# Plots of mean difference
```{r}

df.diff <- df.mean_diff %>% group_by(dataset, parameter, attempts_disc,upsampled) %>% #,attempts, student_question_ratio
  summarize(
    mn = mean(mean_diff),
    sd = sd(mean_diff),
    min = min(mean_diff),
    max = max(mean_diff),
    var = var(mean_diff)
    
  )

df.diff

```


# Plot for poster presentation



```{r}

df.disp <- df.diff %>% filter(!is.nan(sd)) %>% group_by(dataset, parameter)%>% arrange(dataset, parameter, attempts_disc,upsampled) %>% 
  mutate(first = first(var)) %>% mutate(diff_from_first = ((var-first)/first)) %>%
  group_by(upsampled, add = TRUE) %>% mutate(
                                              diff_from_first_disp = rep(c(FALSE,TRUE), length.out = n())) %>%
  ungroup() %>% mutate( diff_from_first_disp = ifelse(diff_from_first_disp, paste0(round(diff_from_first*100,2),"%"), NA), 
                                              )

gg.plot <- df.disp %>%
  
  ggplot() + 
  aes(x= attempts_disc, y = var, color = upsampled) + #avg_attempts
  geom_line(aes(group = upsampled), size = 1.3) + 
  #geom_line(aes(y = mn, group = dataset), size = 1.3, color = "Gray") + 
  geom_point(size = 3) +
  #geom_col() +
  facet_grid(parameter~dataset,scales = "free") + 
  
  labs(x = "Examinee Attempt Size (EAS) of Item", 
       y = "Percentage Drop in Variance", 
       title = "Measure of Spread of Sampling Mean Difference",
       color = "") +
  
  geom_label_repel(aes(label = diff_from_first_disp), size = 3.6, direction = "y", color = "black") + #round(var,2), ";", , force = 10, label.padding = 0.15
  theme_pubclean() + theme(legend.position = "bottom")

gg.plot

```


```{r}

gg.plot <- df.diff %>% #group_by(dataset, parameter)%>% arrange(dataset, parameter, attempts_disc) %>% 
  #mutate(first = first(mn)) %>% mutate(diff_from_first = ((mn-first)/first) ) %>% 
  
  ggplot() + 
  aes(x= attempts_disc, y = mn) + #avg_attempts
  geom_line(aes(group = dataset), size = 1.3) + 
 
  facet_grid(dataset~parameter,scales = "free") + 
  
  labs(x = "Examinee Attempts on Item", 
       y = "Mean", 
       title = "Measure of Spread of Sampling Mean Difference") +
  
   geom_text_repel(aes(label = paste0(round(mn,2))), size = 3.6, direction = "y") + #round(var,2), ";", 
  theme_pubclean()

gg.plot

```

## Outliers

```{r}



```


# Item parameter difference between partitions

```{r}
df.mean_diff
```



```{r}

# Known error: SP dataset for 20 attempts is giving null
#df.t <- df.diff %>% filter(!is.nan(sd))

#df.t <- df.t %>% group_by(dataset, parameter)%>% arrange(dataset, parameter, attempts_disc,upsampled) %>% 
#  mutate(first = first(var)) %>% mutate(diff_from_first = ((var-first)/first)) %>%
#  group_by(upsampled, add = TRUE) %>% mutate(
#                                              diff_from_first_disp = rep(c(FALSE,TRUE), length.out = n())) %>%
#  ungroup() %>% mutate(
#                      diff_from_first_disp = ifelse(diff_from_first_disp, paste0(round(diff_from_first*100,2),"%"), NA), 
#  ) 

#df.t <- df.mean_diff %>% group_by(parameter, dataset, attempts_disc, upsampled) %>% summarise(outlier_count = length(boxplot.stats(mean_diff)$out), n = n())

df.mean_diff %>% #filter(dataset != "Social Psychology") %>%  #mutate(avg_attempts = as.integer(avg_attempts)) %>%
  ggplot() + 
  
  aes(x =attempts_disc, y = mean_diff, color = upsampled) + 
  geom_boxplot() + 
  facet_grid(parameter~dataset, scales = "free") + 
  labs(title = "Distribution of Difference between Item parameters in 2 sub-populations", x = "Examinee Attempt Size (EAS) of Item", y = "Difference of Sampling Mean", color = "")+ 
  theme_pubclean() + theme(legend.position = "bottom")  +
   geom_text(data = df.disp, aes(x=attempts_disc, y = 0.3, label = diff_from_first_disp, color = "Percentage Drop in variance"))   #paste0(round(outlier_count / n,2) * 100, "%")


```


```{r}

df.t <- df.mean_diff %>% group_by(parameter, dataset, student_question_ratio) %>% summarise(outlier_count = length(boxplot.stats(mean_diff)$out), n = n())

df.mean_diff %>% #filter(dataset != "Social Psychology") %>%  #mutate(avg_attempts = as.integer(avg_attempts)) %>%
  ggplot() + 
  
  aes(x =student_question_ratio, y = mean_diff, color = upsampled) + 
  geom_boxplot() + 
  facet_grid(parameter~dataset, scales = "free") + 
  labs(title = "Distribution of Difference between Item parameters in 2 sub-populations", x = "Student to Question Ratio (Sample Batches)", y = "Difference of Sampling Mean", color = "")+ 
  theme_pubclean() + theme(legend.position = "bottom")  +
  geom_text(data = df.t, aes(x=student_question_ratio, y = 1.2, label = paste0(round(outlier_count / n,2) * 100, "%"), color = "Outlier Percentage"))  
  


```




```{r}

df.mean_diff  %>% #filter(dataset == "Social Psychology" | avg_attempts > 14) %>%
  
  
  ggplot() + 
  aes(y=attempts_disc, x=mean_diff) +
  
  geom_density_ridges(aes(height = ..density..), 
                      stat = "density", rel_min_height=0.01, 
                      alpha = 0.3
                       ) +
  
  #labs(y = "Student count (average) attempting each item", x = "Mean Difference between partitions", title = "") + 
  labs(y = "Student count (average) attempting each item", x = "Item-Parameter Bias Relative difference", title = "") + 
  geom_vline(aes(xintercept = 0.02), linetype = 2) + 
  geom_vline(aes(xintercept = -0.02), linetype = 2) + 
  #theme_pubclean() + 
  facet_grid(dataset ~ parameter, scales = "free", 
             labeller = label_wrap_gen(width = 10, multi_line = FALSE))  + 
    theme(axis.text.x = element_text(size = 12), 
          axis.text.y = element_text(size = 10.5),
          strip.text.x = element_text(size = 14),
          strip.text.y = element_text(size = 14),
          axis.title.x = element_text(size = 18),
          axis.title.y = element_text(size = 16)
          
          ) #+ scale_x_continuous(limits = c(-3,3), breaks = seq(-3,3,1))

  
```



# EDA Model Fit

Need to take average because for different sample sizes there can be same number of attempts

```{r}

df.fit.plot.attempts <- df.fit.plot %>% group_by(group, parameter, fit, dataset, sample_size) %>% summarise_all(.funs = mean)
#df.fit.plot.attempts
```


```{r}


df.fit.plot.attempts %>% arrange(sample_size) %>% distinct(group, sample_size, dataset) %>% filter(dataset == "Social Psychology (Upsample)") %>% filter(group == "Partition 2")

```


```{r}

df.fit.plot.attempts %>% #filter(group == "Partition 1") %>%
  
  ggplot() +
  aes(x=attempts, y=sampling_error, color = dataset, group = group) +
  geom_line() +
  geom_label(aes(label = round(sampling_error,6)))+
  geom_hline(aes(yintercept=0.05),linetype="dotted") +
  #scale_x_continuous(limits = c(0,300)) + 
  facet_grid(group~dataset,scales = "free")
  
  
  
  

```





