---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---



```{r}
library(tidyverse)
library(CDM)
library(dina)
```


```{r}
X = data.ecpe$data  %>% select(-id)
Q = data.ecpe$q.matrix

#Simulate X
X = matrix(round(rbeta(50*18, 1, 1)), ncol=18)
Q = matrix(round(rbeta(18*6, 1, 1)), ncol=6)

```

```{r}
#round(rbeta(10,1,2))
```


```{r}
dim(X)
```

```{r}
dim(Q)
```


```{r}
```


```{r}
model_dina <- din(X, Q)
model_dina

```


```{r}

model_dina$subj.pattern


```

```{r}

head(IRT.factor.scores(model_dina, type = "MAP"))


```


```{r}
chainLength = 200
burnin = 100
N = 2922
K = 3
J = 28
```

```{r}

outchain <- dina(as.matrix(X %>% select(-id)), as.matrix(Q), chain_length = chainLength)

```

```{r}
summary(model_dina)
```



```{r}

# Summarize posterior samples for g and 1-s ----

chain_samples = burnin:chainLength
mGs = apply(outchain$GamS[, chain_samples], 1, mean)
sGs = apply(outchain$GamS[, chain_samples], 1, sd)
m1mSS = 1 - apply(outchain$SigS[, chain_samples], 1, mean)
s1mSS = apply(outchain$SigS[, chain_samples], 1, sd)
output = cbind(mGs, sGs, m1mSS, s1mSS)
colnames(output) = c('g Est', 'g SE', '1-s Est', '1-s SE')
rownames(output) = paste('Item', 1:J)
print(output, digits = 3)

```



```{r}
#As = rep(0,K)
## Summarize marginal skill distribution ---- 

# Via posterior samples for latent class proportions
PIoutput = cbind(apply(outchain$PIs, 1, mean), apply(outchain$PIs, 1, sd))
colnames(PIoutput) = c('EST', 'SE')
#rownames(PIoutput) = apply(As, 1, paste0, collapse='')
print(PIoutput, digits = 3)



```
















