---
title: "CDM Bootstrap Sampling"
output: html_notebook
---


```{r}
library(ggplot2)
library(ggpubr)
library(CDM)
library(boot)
library(tidyverse)
```

# Read Data
```{r}
rm(list = ls())

X = data.ecpe$data
Q = data.ecpe$q.matrix

df.data <- X
df.t <- X %>% mutate(total_marks = rowSums(.[-1]), grand_total = 28, percentage = total_marks / grand_total, 
                     grades = ifelse(percentage >= 0.9, "A",
                                     ifelse(percentage >= 0.8 & percentage < 0.9, "B",
                                            ifelse(percentage >= 0.7 & percentage < 0.8, "C",
                                                   ifelse(percentage >= 0.6 & percentage < 0.7, "D", "F")))
                                     ), grades = factor(grades)) %>% 
  mutate(mastery = factor(case_when(
    grades == "A" | grades == "B" ~ "Mastery",
    grades == "B" | grades == "C" ~ "Average",
    grades == "D" | grades == "F" ~ "Non-Mastery"))) %>%
  
  select(id, total_marks, grand_total, percentage, grades, mastery) %>% group_by(mastery) %>% mutate(mastery_n = paste0(mastery,"(",n(),")")) %>% ungroup() %>% mutate(mastery = mastery_n)

df.data = df.data %>% inner_join(df.t)
```

```{r}
X
```


# Sum up Marks 

See how the items are performing
```{r}

df.data %>% select(id, mastery, E1:E28) %>% gather(key = "questions", value = "answer", -id, -mastery, factor_key = TRUE) %>% group_by(mastery, questions) %>% summarize( percent_questions_answered = sum(answer) / n()) %>% 
  ggplot() + aes(x=questions, y = percent_questions_answered, color = mastery) + geom_point() + facet_grid(mastery~.) + theme_pubclean()

```



```{r}
total_percent_fn <- function(df, i = 1:dim(df)[1]) {
  
  #browser()
  df.t <- df[i,]
  #df.t <- df.data
 df.t <- df.t %>% select(id, mastery, E1:E28) %>% gather(key = "questions", value = "answer", -id, -mastery, factor_key = TRUE) %>% group_by(mastery, questions) %>% summarize( percent_questions_answered = sum(answer) / n()) %>% unite("questions",mastery, questions) %>% ungroup()
 
 col_order = df.t$questions
 
 df.t1 <- df.t %>% spread(key=1, value = percent_questions_answered, convert = TRUE)  %>% select(!!!col_order)
 
 return(as.matrix(df.t1))
    
} 

t <- total_percent_fn(df.data)

t
```


```{r}

X.bt <- boot(data = df.data , statistic = total_percent_fn, R = 10, stype = "i")

plot(X.bt)
```

```{r}
#X.bt$t
```

# Extract Data structure for different data divisions

```{r}

df.group_mastery <- X.bt$t[,1:28] %>% as_tibble() %>% mutate(group = "Mastery")
df.group_ave <- X.bt$t[,29:56] %>% as_tibble() %>% mutate(group = "Average")
df.group_non_mastery <- X.bt$t[,57:84] %>% as_tibble() %>% mutate(group = "Non-Mastery")

df.data.sim <- df.group_mastery %>% bind_rows(df.group_ave) %>% bind_rows(df.group_non_mastery)
df.data.sim


```

```{r}
df.t <- df.data.sim
col_names <- colnames(df.t %>% select(-group)) %>% str_replace("V","Q")

df.t %>% gather(key = "questions", value="percent_questions_answered", -group) %>% mutate(questions = factor(str_replace(questions, "V","Q"), levels = col_names, ordered = TRUE)) %>% group_by(group, questions) %>% summarise( sampling_mean = mean(percent_questions_answered), 
                                                                                                                                                                                                                                 sampling_error = sqrt(sum((percent_questions_answered - sampling_mean)^2)/(n() - 1)) )

```

```{r}

df.t %>% gather(key = "questions", value="percent_questions_answered", -group) %>% mutate(questions = factor(str_replace(questions, "V","Q"), levels = col_names, ordered = TRUE)) %>% group_by(group, questions) %>% summarise( sampling_mean = mean(percent_questions_answered), 
                                                                                                                                                                                                                                 sampling_error = sqrt(sum((percent_questions_answered - sampling_mean)^2)/(n() - 1)) ) %>% 
  
  ggplot() + aes(x=questions, y = sampling_mean, color = group) + facet_grid(group ~ .)  +geom_errorbar( aes(ymin=sampling_mean - sampling_error, 
                                                                                                                          ymax=sampling_mean + sampling_error), width=.2) + geom_point(size = 1) + ggtitle("Percentage of students who answered the question right")


```

# CDM Estimation

```{r}

library(CDM)

model_dina <- din(X %>% select(-id), Q)
model_dina$slip

```



## Calculate item parameters

```{r}
library(CDM)
total_cdm_fn <- function(df, i = 1:dim(df)[1]) {
  
  #browser()
  df.t <- df.data
  df.t <- df[i,]
  
  df.t.mastery <- df.t %>% filter(str_detect(mastery,"^Mastery(.)")) %>% select(E1:E28)
  df.t.ave <- df.t %>% filter(str_detect(mastery, "^Average(.)")) %>% select(E1:E28)
  df.t.non_mastery <- df.t %>% filter(str_detect(mastery,"^Non-Mastery(.)")) %>% select(E1:E28)
 
  ###########################
  
  df.cdm <- CDM::din(df.t.mastery, Q, progress=FALSE)
  df.profile <- IRT.factor.scores(df.cdm, type = "MAP") 

 
   df.t1 <- tibble("value" = df.cdm$slip$est, "key" = paste0("mastery_slip_E", seq(1,28,1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("mastery_slip_E", seq(1,28,1)))
 
  
  df.t2 <- tibble("value" = df.cdm$guess$est, "key" = paste0("mastery_guess_E", seq(1,28,1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("mastery_guess_E", seq(1,28,1)))
  
  df.p1 <- tibble("value" = df.profile[,1], "key" = paste0("mastery_subj_id", seq(1,length(df.profile[,1]),1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("mastery_subj_id", seq(1,length(df.profile[,1]),1)))
  
  ###########################
 
  df.cdm <- CDM::din(df.t.ave, Q, progress=FALSE)
  df.profile <- IRT.factor.scores(df.cdm, type = "MAP") 
 
  df.t3 <- tibble("value" = df.cdm$slip$est, "key" = paste0("average_slip_E", seq(1,28,1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("average_slip_E", seq(1,28,1)))
 
  
  df.t4 <- tibble("value" = df.cdm$guess$est, "key" = paste0("average_guess_E", seq(1,28,1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("average_guess_E", seq(1,28,1)))
  
  df.p2 <- tibble("value" = df.profile[,1], "key" = paste0("average_subj_id", seq(1,length(df.profile[,1]),1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("average_subj_id", seq(1,length(df.profile[,1]),1)))
  
  #############################
  
  df.cdm <- CDM::din(df.t.non_mastery, Q, progress=FALSE)
  df.profile <- IRT.factor.scores(df.cdm, type = "MAP") 
 
  df.t5 <- tibble("value" = df.cdm$slip$est, "key" = paste0("non_mastery_slip_E", seq(1,28,1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("non_mastery_slip_E", seq(1,28,1)))
 
  
  df.t6 <- tibble("value" = df.cdm$guess$est, "key" = paste0("non_mastery_guess_E", seq(1,28,1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("non_mastery_guess_E", seq(1,28,1)))
  
  df.p3 <- tibble("value" = df.profile[,1], "key" = paste0("non_mastery_subj_id", seq(1,length(df.profile[,1]),1))) %>% spread(key = "key", value = "value") %>% select(!!!paste0("non_mastery_subj_id", seq(1,length(df.profile[,1]),1)))
  
  df.t <- cbind(df.t1, df.t2, df.t3, df.t4, df.t5, df.t6, df.p1, df.p2, df.p3)
  print(dim(df.p1))
  print(dim(df.p2))
  print(dim(df.p3))
  
  
 return(as.matrix(df.t))
    
} 

t_cdm <- total_cdm_fn(df.data)

head(as.data.frame(t_cdm ))
```



```{r}

X.bt <- boot(data = df.data , statistic = total_cdm_fn, R = 5, stype = "i")

plot(X.bt)
```

```{r}


#unique(df.data$mastery_n)



df.m_slip <- X.bt$t[,1:28] %>%  as_tibble() %>% mutate(parameter = "Slip", group = unique(df.data$mastery)[str_detect( unique(df.data$mastery) ,"^Mastery.")])
df.m_guess <- X.bt$t[,29:56] %>% as_tibble() %>% mutate(parameter = "Guess", group = unique(df.data$mastery)[str_detect( unique(df.data$mastery) ,"^Mastery.")])


df.ave_slip <- X.bt$t[,57:84] %>%  as_tibble() %>% mutate(parameter = "Slip", group = unique(df.data$mastery)[str_detect( unique(df.data$mastery) ,"^Average.")])
df.ave_guess <- X.bt$t[,85:112] %>% as_tibble() %>% mutate(parameter = "Guess", group = unique(df.data$mastery)[str_detect( unique(df.data$mastery) ,"^Average.")])


df.nm_slip <- X.bt$t[,113:140] %>%  as_tibble() %>% mutate(parameter = "Slip", group = unique(df.data$mastery)[str_detect( unique(df.data$mastery) ,"^Non-Mastery.")])
df.nm_guess <- X.bt$t[,141:168] %>% as_tibble() %>% mutate(parameter = "Guess", group = unique(df.data$mastery)[str_detect( unique(df.data$mastery) ,"^Non-Mastery.")])


df.m_profile <- X.bt$t %>%  as_tibble() %>% 
  select(contains("mastery_subj")) %>%
  mutate(parameter = "Slip", group = unique(df.data$mastery)[str_detect( unique(df.data$mastery) ,"^Mastery.")])


df.data.sim <- df.m_slip %>% bind_rows(df.m_guess) %>% 
  bind_rows(df.ave_slip) %>% bind_rows(df.ave_guess) %>% 
  bind_rows(df.nm_slip) %>% bind_rows(df.nm_guess)  #%>%
  #mutate(group = factor(group, levels = c("Mastery(954)", "Average(700)", "Non-Mastery(1268)"), ordered = TRUE))

df.data.sim

```

```{r}
df.t <- df.data.sim
col_names <- colnames(df.t %>% select(-group)) %>% str_replace("V","Q")

df.t %>% gather(key = "questions", value="item_parameters", -group, -parameter) %>% mutate(questions = factor(str_replace(questions, "V","Q"), levels = col_names, ordered = TRUE)) %>% group_by(group, parameter, questions) %>% summarise( sampling_mean = mean(item_parameters), 
                                                                                                                                                                                                                                 sampling_error = sqrt(sum((item_parameters - sampling_mean)^2)/(n() - 1)) )
```


```{r}

df.t %>% gather(key = "questions", value="item_parameters", -group, -parameter) %>% mutate(questions = factor(str_replace(questions, "V","Q"), levels = col_names, ordered = TRUE)) %>% group_by(group, parameter, questions) %>% summarise( sampling_mean = mean(item_parameters), 
                                                                                                                                                                                                                                 sampling_error = sqrt(sum((item_parameters - sampling_mean)^2)/(n() - 1)) ) %>% 
  
  ggplot() + aes(x=questions, y = sampling_mean, color = parameter) + facet_grid(group ~ .  )  +geom_pointrange( aes(ymin=sampling_mean - sampling_error, 
                                                                                                                          ymax=sampling_mean + sampling_error), width=.2) + geom_point(size = 1) + theme(strip.text.y = element_text(angle = 0)) + ggtitle("Item Parameters estimated over 1000 Bootstrap samples")


```




```{r}

df.t  %>% gather(key = "questions", value="item_parameters", -group, -parameter) %>% mutate(questions = factor(str_replace(questions, "V","Q"), levels = col_names, ordered = TRUE)) %>% group_by(group, parameter, questions) %>% summarise( sampling_mean = mean(item_parameters), 
                                                                                                                                                                                                                                 sampling_error = sqrt(sum((item_parameters - sampling_mean)^2)/(n() - 1)) ) %>% 
  
  ggplot() + aes(x=questions, y = sampling_mean, color = group) + facet_grid(parameter ~ questions, scales = "free_x"  )  +
  
  geom_pointrange(position=position_dodge(width=0.5), aes(ymin=sampling_mean - sampling_error, ymax=sampling_mean + sampling_error), width=.2) +
  
  geom_point(position=position_dodge(width=0.5), size = 1) + theme(strip.text.y = element_text(angle = 0)) + ggtitle("Item Parameters estimated over 1000 Bootstrap samples") + theme(axis.text.x = element_text() , strip.background.x = element_rect(fill = "white"), axis.ticks.x = element_blank()) + labs(x="Questions / Items", y = "Sampling Mean with Sampling error") + scale_color_brewer(palette="Dark2")


```








# Plotting without error bars


```{r}

df.t %>% gather(key = "questions", value="item_parameters", -group, -parameter) %>% mutate(questions = factor(str_replace(questions, "V","Q"), levels = col_names, ordered = TRUE)) %>% group_by(group, parameter, questions) %>% summarise( sampling_mean = mean(item_parameters), 
                                                                                                                                                                                                                                 sampling_error = sqrt(sum((item_parameters - sampling_mean)^2)/(n() - 1)) ) %>% 
  
  ggplot() + aes(x=questions, y = sampling_mean, color = parameter) + facet_grid(group ~ .  )  + geom_point(size = 1) + theme(strip.text.y = element_text(angle = 0)) + ggtitle("Item Parameters estimated over 1000 Bootstrap samples")


```




```{r}

df.t  %>% gather(key = "questions", value="item_parameters", -group, -parameter) %>% mutate(questions = factor(str_replace(questions, "V","Q"), levels = col_names, ordered = TRUE)) %>% group_by(group, parameter, questions) %>% summarise( sampling_mean = mean(item_parameters), 
                                                                                                                                                                                                                                 sampling_error = sqrt(sum((item_parameters - sampling_mean)^2)/(n() - 1)) ) %>% 
  
  ggplot() + aes(x=questions, y = sampling_mean, color = group) + facet_grid(parameter ~ questions, scales = "free"  ) + geom_point(position=position_dodge(width=0.5), size = 1) + theme(strip.text.y = element_text(angle = 0)) + ggtitle("Item Parameters estimated over 1000 Bootstrap samples") + theme(axis.text.x = element_text() , strip.background.x = element_rect(fill = "white"), axis.ticks.x = element_blank()) + labs(x="Questions / Items", y = "Sampling Mean with Sampling error") + scale_color_brewer(palette="Dark2")


```


































