---
title: "R Notebook"
output: html_notebook
---



```{r}

library(ggplot2)
library(ggpubr)
library(CDM)
library(boot)
library(tidyverse)
library(dummy)
library(stringi)
library(stringr)


```


```{r}

rm(list = ls())

Q_from_book <- read_csv("../data//FirstYearProject/final_result_similar.csv")

glimpse(Q_from_book)

```



```{r}

Q_from_book

```


```{r}
#, `Skill Level`, `Difficulty Level` 
learning_obj <- Q_from_book %>% distinct(`Skill Level`, `APA Learning Objective`) %>% mutate(lo_id = row_number())
learning_obj

```


```{r}


Q_pre <- Q_from_book %>% inner_join(learning_obj) %>% select(Question, `Skill Level`, `Difficulty Level`, lo_id) %>% mutate(temp = str_trim(str_replace_all(Question, "_|\\.", "")))
Q_pre

```


```{r}

Q.distinct.id <- read_csv("../data/FirstYearProject/Q_distinct_id.csv") 

Q.distinct.id <- Q.distinct.id %>% mutate(temp = str_trim(str_replace_all(value, "_|\\.", "")))
Q.distinct.id
```


# Work on this line
```{r}

Q_pre %>% inner_join(Q.distinct.id, by = "temp") 

```


```{r}

Q <- Q_pre %>% inner_join(Q.distinct.id, by = "temp") %>% distinct(Q_UNIQUE_ID, lo_id) %>% arrange(Q_UNIQUE_ID) %>%
  mutate(present = 1) %>%
  
  spread(key = "lo_id", value = "present")

Q


Q %>% write_csv("data\\Q.csv")

```


```{r}

Q_pre %>% anti_join(Q.distinct.id) %>% distinct(Question, temp) %>% select(-temp ) %>% write_csv("missing.csv")

```

